name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Plan / Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Autenticarse en GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar sintaxis
        run: terraform validate

      - name: Plan (Pull Request)
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Apply (Main branch)
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: terraform apply -auto-approve

      - name: Debug evento
        run: echo "event=${{ github.event_name }} ref=${{ github.ref }} ref_name=${{ github.ref_name }}"